version: '3.8'
services:
  app:
    image: node:14-alpine
    volumes:
      - ./docker/volumes/node/config:/config
      - ./:/app
    working_dir: /app
    command: npm run start:dev
    env_file: ./docker/volumes/node/config/.env

  scripts:
    image: curlimages/curl:7.85.0
    profiles:
      - scripts
    volumes: 
      - ./bash:/scripts
    working_dir: /scripts
    env_file: ./docker/volumes/node/config/.env

  gcp:
    image: google/cloud-sdk:latest
    profiles:
      - scripts

volumes:
  gcp: