version: '3.8'
services:
  app:
    depends_on:
      - mqtt
      - zigbee2mqtt
    image: bdvs/iot-nest-firmware:0.0.1
    volumes:
      - /device-data/node/config:/config
    working_dir: /app/dist
    command: node /app/dist/main
    env_file: /device-data/node/config/.env

  mqtt:
    image: eclipse-mosquitto:2.0
    restart: unless-stopped
    volumes:
      - "/device-data/mosquitto/mosquitto-data:/mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    command: "mosquitto -c /mosquitto-no-auth.conf"

  zigbee2mqtt:
    depends_on:
      - mqtt
    restart: unless-stopped
    image: koenkk/zigbee2mqtt:1.28.0
    volumes:
      - /device-data/zigbee2mqtt/zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8081:8080
    environment:
      - TZ=Europe/London
    devices:
      - /dev/ttyACM0:/dev/ttyACM0

  scripts:
    image: bdvs/iot-scripts:0.0.1
    profiles: 
      - scripts
    env_file: /device-data/node/config/.env
    entrypoint: /bin/sh