version: '3.8'
services:
  app:
    image: node:14-alpine
    profiles: 
      - app
    volumes:
      - ~/.config/device/:/config
      - ./:/app
    working_dir: /app
    command: npm run start:dev
    env_file: ./.env
    networks:
      - mqtt-broker_bdvs-iot

  mqtt:
    image: eclipse-mosquitto:2.0
    profiles: 
      - mqtt
    restart: always
    volumes:
      - "~/.config/mosquitto/mosquitto-data:/mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    command: "mosquitto -c /mosquitto-no-auth.conf"
    networks:
      - mqtt-broker_bdvs-iot

  zigbee2mqtt:
    depends_on:
      - mqtt
    restart: always
    image: koenkk/zigbee2mqtt:1.28.0
    profiles: 
      - mqtt
    volumes:
      - ~/.config/zigbee2mqtt/zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8081:8080
    environment:
      - TZ=Europe/London
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    networks:
      - mqtt-broker_bdvs-iot

  scripts:
    image: curlimages/curl:7.85.0
    profiles:
      - scripts
    volumes: 
      - ./bash:/scripts
    working_dir: /scripts
    env_file: ~/.config/device/.env

  gcp:
    image: google/cloud-sdk:latest
    profiles:
      - scripts

volumes:
  gcp:

networks:
  mqtt-broker_bdvs-iot:
    external: true