version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.App
    image: iot-nest-firmware:latest
    profiles: 
      - app
    restart: always
    privileged: true
    devices:
      - /dev/gpiomem:/dev/gpiomem
    volumes:
      - ~/.config/device/:/config
    working_dir: /app/dist
    command: node /app/dist/main
    env_file: ~/.config/device/.env

  mqtt:
    image: eclipse-mosquitto:2.0
    profiles: 
      - mqtt
    volumes:
      - "~/.config/mosquitto/mosquitto-data:/mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    command: "mosquitto -c /mosquitto-no-auth.conf"

  zigbee2mqtt:
    depends_on:
      - mqtt
    restart: always
    image: koenkk/zigbee2mqtt:2.6.2
    profiles: 
      - mqtt
    volumes:
      - ~/.config/zigbee2mqtt/zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8081:8080
    environment:
      - TZ=Europe/London
    devices:
      - /dev/ttyACM0:/dev/ttyACM0

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    profiles: 
      - app
    restart: always