services:

  mqtt:
    image: eclipse-mosquitto:2.0
    profiles: 
      - mqtt
    volumes:
      - "~/.config/mosquitto/mosquitto-data:/mosquitto"
    ports:
      - "1883:1883"
      - "9001:9001"
    command: "mosquitto -c /mosquitto-no-auth.conf"

  zigbee2mqtt:
    depends_on:
      - mqtt
    restart: always
    image: koenkk/zigbee2mqtt:2.6.2
    profiles: 
      - mqtt
    volumes:
      - ~/.config/zigbee2mqtt/zigbee2mqtt-data:/app/data
      - /run/udev:/run/udev:ro
    ports:
      - 8081:8080
    environment:
      - TZ=Europe/London
    devices:
      - /dev/ttyACM0:/dev/ttyACM0